# Generated by Django 6.0 on 2026-01-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "calendar_file",
                    models.FileField(
                        upload_to="calendars/", verbose_name="Calendar Field"
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Month",
                "verbose_name_plural": "Calendar Months",
                "ordering": ["-year", "-month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("month", "year"), name="unique_month_year"
                    )
                ],
            },
        ),
    ]
