# Generated by Django 6.0 on 2026-01-03 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="calendar_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("parsed_data", models.JSONField(blank=True, null=True)),
                ("successfully_parsed", models.BooleanField(default=False)),
                ("month", models.IntegerField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "notes_or_announcements",
                    models.JSONField(blank=True, default=list, null=True),
                ),
            ],
            options={
                "verbose_name": "Calendar Month",
                "verbose_name_plural": "Calendar Months",
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(verbose_name="Day of the month (1-31)")),
                (
                    "hour",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Hour of the event (1-12)"
                    ),
                ),
                (
                    "minute",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Minute of the event (0-59)"
                    ),
                ),
                (
                    "am_pm",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="am or pm"
                    ),
                ),
                ("title", models.TextField(verbose_name="Title of the event")),
                (
                    "color",
                    models.CharField(
                        default="black",
                        max_length=50,
                        verbose_name="Color of the event",
                    ),
                ),
                ("all_day", models.BooleanField(default=False, verbose_name="All day")),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                ("original_text", models.TextField(verbose_name="The exact raw text")),
                (
                    "calendar_month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="grandpa.calendarmonth",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Event",
                "verbose_name_plural": "Calendar Events",
                "ordering": ["-day", "-hour", "-minute"],
            },
        ),
    ]
