# Generated by Django 6.0 on 2026-01-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grandpa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="calendar_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("parsed_data", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
